### Analyze Blood Glucose Data
POST http://localhost:9090/api/analyzeBloodGlucose
Content-Type: application/json

{
  "fastingGlucose": 15,
  "randomGlucose": 130,
  "hba1c": 5.5
}

### Analyze C-Reactive Protein (CRP) Data
POST http://localhost:9090/api/analyzeCRP
Content-Type: application/json

{
  "crpLevel": 2.5
}

### Analyze Full Blood Count (FBC) Data
POST http://localhost:9090/api/analyzeFBC
Content-Type: application/json

{
  "whiteBloodCells": 5.0,
  "redBloodCells": 4.5,
  "hemoglobin": 15.0,
  "platelets": 250
}

### Analyze Lipid Panel Data
POST http://localhost:9090/api/analyzeLipidPanel
Content-Type: application/json

{
  "cholesterol": 180,
  "triglycerides": 140,
  "hdl": 55,
  "ldl": 120
}

### Analyze Liver Function Test Data
POST http://localhost:9090/api/analyzeLFT
Content-Type: application/json

{
  "alt": 35,
  "ast": 30,
  "alp": 100,
  "bilirubin": 0.8
}

### Analyze Thyroid Function Test Data
POST http://localhost:9090/api/analyzeTFT
Content-Type: application/json

{
  "tsh": 2.5,
  "t3": 1.5,
  "t4": 10.5
}

### Get all users
GET http://localhost:9090/api/users
Accept: application/json

###

### Signup Request
POST http://localhost:9090/api/signup
Content-Type: application/json

{
    "username": "testuser",
    "first_name": "Test",
    "last_name": "User",
    "email": "testuser@example.com",
    "password": "password123"
}

### Login Request
POST http://localhost:9090/api/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "password123"
}

### Get User by Email Request
POST http://localhost:9090/api/userByEmail
Content-Type: application/json

{
    "email": "testuser@example.com"
}

### Forgot Password Request
POST http://localhost:9090/api/forgotPassword
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "newpassword123"
}

### DELETE USER 
DELETE http://localhost:9090/api/deleteUser
Content-Type: application/json

{
    "email": "rathnayakermib.22@uom.lk"

}
